### Merge behavioral variables with subtypes weights

In [1]:
# Import pandas
import os
import pandas as pd
import numpy as np

In [2]:
# Set up the paths to the files we want to work with
base_path = "/media/yassinebha/database27/Drive/HCP/subtypes_scores/26-10-2016/subtype_5_MOTOR_RL_08-Dec-2016/networks/"
sbt_name_pattern = "sbt_weights_net_{}.csv"
pheno_path = '/media/yassinebha/database27/Drive/HCP/subtypes_scores/26-10-2016/pheno/'
out_path = '/media/yassinebha/database27/Drive/HCP/Solar_heritability/HCP_subtype/'
# List of network names
net_names = ["MOT_FACE_L",  "MOT_FACE_R",  "MOT_HAND_L",  "MOT_HAND_R", "MOT_LEG_L", "MOT_LEG_R"]

In [3]:
for index, net in enumerate(net_names):
    file_path = os.path.join(base_path, net, sbt_name_pattern.format(net))
    if not os.path.exists(file_path):
        print("Hello, {} does not exist".format(file_path))
    
    tmp_weights = pd.read_csv(file_path)
    # Rename first column
    tmp_weights.rename(columns={" ":"Subject"}, inplace=True)
    tmp_weights.Subject = tmp_weights.Subject.str.strip(" ")
    
    rename_dict = dict()
    for colname in tmp_weights.columns:
        if colname == "Subject":
            continue
        else:
            new_name = "{}_{}".format(net, colname)
            # Get rid of trailing whitespace
            new_name = new_name.strip(" ")
            rename_dict[colname] = new_name

    tmp_weights.rename(columns=rename_dict, inplace=True)
    
    if index==0:
        dataframe = tmp_weights
    else:
        dataframe = pd.merge(dataframe, tmp_weights, on="Subject", how="inner")

In [4]:
dataframe.head()

,Subject,MOT_FACE_L_sub1,MOT_FACE_L_sub2,MOT_FACE_L_sub3,MOT_FACE_L_sub4,MOT_FACE_L_sub5,MOT_FACE_R_sub1,MOT_FACE_R_sub2,MOT_FACE_R_sub3,MOT_FACE_R_sub4,...,MOT_LEG_L_sub1,MOT_LEG_L_sub2,MOT_LEG_L_sub3,MOT_LEG_L_sub4,MOT_LEG_L_sub5,MOT_LEG_R_sub1,MOT_LEG_R_sub2,MOT_LEG_R_sub3,MOT_LEG_R_sub4,MOT_LEG_R_sub5
0,HCP100206,0.120,0.031,-0.179,-0.248,0.221,0.157,-0.172,-0.171,0.219,...,-0.064,0.073,-0.102,0.142,-0.088,0.146,0.023,-0.132,0.045,-0.115
1,HCP100307,-0.080,0.218,0.216,-0.108,-0.143,-0.136,0.098,0.269,-0.193,...,0.090,-0.081,0.065,-0.135,0.108,0.091,-0.040,-0.085,0.083,-0.048
2,HCP100408,0.092,-0.107,-0.321,-0.326,0.461,0.456,-0.405,-0.085,0.168,...,-0.143,0.200,-0.117,0.134,-0.106,0.208,-0.030,-0.133,0.057,-0.146
3,HCP100610,-0.168,-0.259,-0.114,0.087,0.234,0.323,-0.117,-0.113,0.157,...,0.060,-0.170,0.012,-0.043,0.141,-0.149,-0.100,0.119,-0.041,0.224
4,HCP101006,-0.338,0.037,0.109,0.346,-0.207,0.047,-0.101,0.126,-0.142,...,-0.003,-0.018,0.195,-0.303,0.202,-0.232,0.101,0.135,-0.242,0.246

In [5]:
# Merge weight with pheno 
file_weight = dataframe
file_pheno = pd.read_csv(os.path.join(pheno_path,"motor_RL_pheno_scrub_raw.csv"))

In [6]:
file_pheno.head()

,Subject,Age_in_Yrs,Twin_Stat,Zygosity,Mother_ID,Father_ID,Handedness,BMI,Gender,Endurance_Unadj,...,GaitSpeed_Comp,Dexterity_Unadj,Dexterity_AgeAdj,Strength_Unadj,Strength_AgeAdj,Odor_Unadj,PainInterf_Tscore,Taste_Unadj,FD,FD_scrubbed
0,HCP100206,27,NotTwin,NotTwin,56037,85858.0,65,26.64,M,123.31,...,1.24,106.61,94.23,132.46,129.43,108.79,49.7,72.63,0.090883,0.090883
1,HCP100307,27,Twin,NotMZ,51488,81352.0,95,22.96,F,114.05,...,1.58,118.68,105.21,108.34,84.59,101.12,38.6,71.69,0.108998,0.108998
2,HCP100408,33,Twin,MZ,51730,81594.0,55,27.75,M,121.00,...,1.51,117.48,106.24,125.18,124.24,108.79,52.6,114.01,0.098323,0.098323
3,HCP100610,27,Twin,NotMZ,52813,82634.0,85,36.91,M,107.24,...,1.10,121.55,107.85,123.16,118.90,122.25,38.6,84.84,0.139763,0.137298
4,HCP101006,35,Twin,MZ,51283,81149.0,90,30.27,F,81.58,...,1.24,106.53,96.00,116.06,106.93,122.25,38.6,123.80,0.165364,0.138544

In [7]:
# Select a subset of variable
file_pheno_subset = file_pheno[["Subject","Handedness","BMI","FD","FD_scrubbed"]]
file_pheno_subset.head()

     Subject  Handedness    BMI        FD  FD_scrubbed
0  HCP100206          65  26.64  0.090883     0.090883
1  HCP100307          95  22.96  0.108998     0.108998
2  HCP100408          55  27.75  0.098323     0.098323
3  HCP100610          85  36.91  0.139763     0.137298
4  HCP101006          90  30.27  0.165364     0.138544

In [8]:
file_pheno_subset[["Subject"]].describe()

          Subject
count         831
unique        831
top     HCP177241
freq            1

In [9]:
file_weight[["Subject"]].describe()

          Subject
count         831
unique        831
top     HCP177241
freq            1

In [10]:
# Merge weight with subset of pheno variables
merged_weight_pheno = pd.merge(file_weight, file_pheno_subset, on='Subject', how='left')
# Replace 'Subject' by 'ID'
merged_weight_pheno.rename(columns={'Subject':'ID'},inplace=True)
merged_weight_pheno.head()

,ID,MOT_FACE_L_sub1,MOT_FACE_L_sub2,MOT_FACE_L_sub3,MOT_FACE_L_sub4,MOT_FACE_L_sub5,MOT_FACE_R_sub1,MOT_FACE_R_sub2,MOT_FACE_R_sub3,MOT_FACE_R_sub4,...,MOT_LEG_L_sub5,MOT_LEG_R_sub1,MOT_LEG_R_sub2,MOT_LEG_R_sub3,MOT_LEG_R_sub4,MOT_LEG_R_sub5,Handedness,BMI,FD,FD_scrubbed
0,HCP100206,0.120,0.031,-0.179,-0.248,0.221,0.157,-0.172,-0.171,0.219,...,-0.088,0.146,0.023,-0.132,0.045,-0.115,65,26.64,0.090883,0.090883
1,HCP100307,-0.080,0.218,0.216,-0.108,-0.143,-0.136,0.098,0.269,-0.193,...,0.108,0.091,-0.040,-0.085,0.083,-0.048,95,22.96,0.108998,0.108998
2,HCP100408,0.092,-0.107,-0.321,-0.326,0.461,0.456,-0.405,-0.085,0.168,...,-0.106,0.208,-0.030,-0.133,0.057,-0.146,55,27.75,0.098323,0.098323
3,HCP100610,-0.168,-0.259,-0.114,0.087,0.234,0.323,-0.117,-0.113,0.157,...,0.141,-0.149,-0.100,0.119,-0.041,0.224,85,36.91,0.139763,0.137298
4,HCP101006,-0.338,0.037,0.109,0.346,-0.207,0.047,-0.101,0.126,-0.142,...,0.202,-0.232,0.101,0.135,-0.242,0.246,90,30.27,0.165364,0.138544

In [11]:
# Check if there is empty value in BMI
sum(merged_weight_pheno.BMI.isnull())

1

In [12]:
# Save the merged file
merged_weight_pheno.to_csv(os.path.join(out_path,"solar_motor_RL_pheno.csv"), index=False)

### Build Pedigree file

In [13]:
# Select a subset of variable from pheno file
file_pheno_pedig = file_pheno[["Subject","Twin_Stat","Zygosity","Mother_ID","Gender"]]

In [14]:
file_pheno_pedig.head()

     Subject Twin_Stat Zygosity  Mother_ID Gender
0  HCP100206   NotTwin  NotTwin      56037      M
1  HCP100307      Twin    NotMZ      51488      F
2  HCP100408      Twin       MZ      51730      M
3  HCP100610      Twin    NotMZ      52813      M
4  HCP101006      Twin       MZ      51283      F

In [15]:
mother_id = ["mo_{}".format(row.Mother_ID) for ind, row in file_pheno_pedig.iterrows()]
father_id = ["fa_{}".format(row.Mother_ID) for ind, row in file_pheno_pedig.iterrows()]
household_id = ["hh_{}".format(row.Mother_ID) for ind, row in file_pheno_pedig.iterrows()]
twin_id = ["pair_{}".format(row.Mother_ID) if row.Zygosity == "MZ" else "" for ind, row in file_pheno_pedig.iterrows()]

In [16]:
file_pheno_pedig["mo"] = mother_id
file_pheno_pedig["fa"] = father_id
file_pheno_pedig["hhID"] = household_id
file_pheno_pedig["mz_twin"] = twin_id
file_pheno_pedig["sex"] = file_pheno_pedig.Gender.replace(to_replace={"M":1, "F":2})

/usr/local/lib/python3.4/dist-packages/ipykernel/__main__.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
/usr/local/lib/python3.4/dist-packages/ipykernel/__main__.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  from ipykernel import kernelapp as app
/usr/local/lib/python3.4/dist-packages/ipykernel/__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
/usr/local/lib/python3.4/dist-packages/ipykernel/__main__.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
/usr/local/lib/python3.4/dist-packages/ipykernel/__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [17]:
uniques = list(file_pheno_pedig.mz_twin.unique())
uniques.pop(0)
twin_counts = [np.sum(file_pheno_pedig.mz_twin==twin) for twin in uniques]

In [18]:
for idx, twin in enumerate(uniques):
    print("{} occurs {} times".format(twin, twin_counts[idx]))

pair_51730 occurs 2 times
pair_51283 occurs 2 times
pair_51679 occurs 2 times
pair_51418 occurs 2 times
pair_51343 occurs 2 times
pair_54643 occurs 2 times
pair_51676 occurs 2 times
pair_51566 occurs 2 times
pair_54572 occurs 1 times
pair_51381 occurs 2 times
pair_51340 occurs 2 times
pair_52925 occurs 1 times
pair_52158 occurs 2 times
pair_51305 occurs 2 times
pair_55793 occurs 2 times
pair_51421 occurs 1 times
pair_51802 occurs 1 times
pair_56022 occurs 1 times
pair_51529 occurs 1 times
pair_51304 occurs 2 times
pair_51477 occurs 2 times
pair_51593 occurs 2 times
pair_52875 occurs 2 times
pair_51347 occurs 2 times
pair_51707 occurs 2 times
pair_51833 occurs 2 times
pair_55705 occurs 2 times
pair_51559 occurs 1 times
pair_52809 occurs 1 times
pair_55694 occurs 2 times
pair_51527 occurs 1 times
pair_52251 occurs 2 times
pair_55825 occurs 2 times
pair_51613 occurs 2 times
pair_51639 occurs 2 times
pair_51672 occurs 2 times
pair_51526 occurs 2 times
pair_51312 occurs 1 times
pair_51279 occurs 2 times
pair_52848 occurs 2 times
pair_52823 occurs 1 times
pair_51702 occurs 2 times
pair_52839 occurs 1 times
pair_52938 occurs 1 times
pair_52326 occurs 2 times
pair_51717 occurs 2 times
pair_52747 occurs 2 times
pair_51628 occurs 2 times
pair_52312 occurs 2 times
pair_52757 occurs 1 times
pair_52874 occurs 2 times
pair_51419 occurs 2 times
pair_51782 occurs 2 times
pair_52273 occurs 2 times
pair_51494 occurs 2 times
pair_52926 occurs 1 times
pair_51599 occurs 1 times
pair_51785 occurs 1 times
pair_55955 occurs 2 times
pair_52801 occurs 1 times
pair_52932 occurs 2 times
pair_51329 occurs 2 times
pair_52269 occurs 2 times
pair_55701 occurs 2 times
pair_52816 occurs 2 times
pair_52753 occurs 2 times
pair_51400 occurs 2 times
pair_56029 occurs 2 times
pair_51459 occurs 2 times
pair_52793 occurs 1 times
pair_56016 occurs 1 times
pair_52872 occurs 2 times
pair_56096 occurs 2 times
pair_51627 occurs 2 times
pair_52884 occurs 1 times
pair_51651 occurs 2 times
pair_52921 occurs 2 times
pair_52873 occurs 2 times
pair_51375 occurs 2 times
pair_54634 occurs 2 times
pair_55699 occurs 2 times
pair_51826 occurs 1 times
pair_52936 occurs 2 times
pair_51689 occurs 2 times
pair_52370 occurs 2 times
pair_52164 occurs 2 times
pair_51377 occurs 2 times
pair_51663 occurs 2 times
pair_51755 occurs 2 times
pair_55686 occurs 2 times
pair_51367 occurs 2 times
pair_55706 occurs 1 times
pair_51673 occurs 1 times
pair_51698 occurs 2 times
pair_55714 occurs 2 times
pair_52141 occurs 1 times
pair_52379 occurs 2 times
pair_51287 occurs 2 times
pair_55651 occurs 2 times
pair_51414 occurs 2 times
pair_52910 occurs 2 times
pair_55732 occurs 1 times
pair_55763 occurs 2 times
pair_56140 occurs 2 times
pair_52913 occurs 1 times
pair_51519 occurs 2 times
pair_51715 occurs 2 times
pair_51465 occurs 2 times
pair_51362 occurs 2 times
pair_52941 occurs 1 times
pair_52795 occurs 1 times
pair_56064 occurs 2 times
pair_51339 occurs 2 times
pair_51561 occurs 1 times
pair_52803 occurs 1 times
pair_52137 occurs 1 times
pair_51290 occurs 1 times
pair_56077 occurs 1 times

In [19]:
singles = [True if np.sum(file_pheno_pedig.mz_twin==row.mz_twin)==1 else False for ind, row in file_pheno_pedig.iterrows()]

In [20]:
file_pheno_pedig.head()

,Subject,Twin_Stat,Zygosity,Mother_ID,Gender,mo,fa,hhID,mz_twin,sex
0,HCP100206,NotTwin,NotTwin,56037,M,mo_56037,fa_56037,hh_56037,,1
1,HCP100307,Twin,NotMZ,51488,F,mo_51488,fa_51488,hh_51488,,2
2,HCP100408,Twin,MZ,51730,M,mo_51730,fa_51730,hh_51730,pair_51730,1
3,HCP100610,Twin,NotMZ,52813,M,mo_52813,fa_52813,hh_52813,,1
4,HCP101006,Twin,MZ,51283,F,mo_51283,fa_51283,hh_51283,pair_51283,2

In [21]:
test = file_pheno_pedig.copy()

In [22]:
single_pedig = test[singles]

In [23]:
for i, row in single_pedig.iterrows():
    single_pedig.set_value(i,"Subject","M_{}".format(row.Subject))

In [24]:
test.append(single_pedig)

,Subject,Twin_Stat,Zygosity,Mother_ID,Gender,mo,fa,hhID,mz_twin,sex
0,HCP100206,NotTwin,NotTwin,56037,M,mo_56037,fa_56037,hh_56037,,1
1,HCP100307,Twin,NotMZ,51488,F,mo_51488,fa_51488,hh_51488,,2
2,HCP100408,Twin,MZ,51730,M,mo_51730,fa_51730,hh_51730,pair_51730,1
3,HCP100610,Twin,NotMZ,52813,M,mo_52813,fa_52813,hh_52813,,1
4,HCP101006,Twin,MZ,51283,F,mo_51283,fa_51283,hh_51283,pair_51283,2
5,HCP101107,NotTwin,NotTwin,51969,M,mo_51969,fa_51969,hh_51969,,1
6,HCP101309,NotTwin,NotTwin,52385,M,mo_52385,fa_52385,hh_52385,,1
7,HCP101410,Twin,NotMZ,52198,M,mo_52198,fa_52198,hh_52198,,1
8,HCP101915,NotTwin,NotTwin,51977,F,mo_51977,fa_51977,hh_51977,,2
9,HCP102008,NotTwin,NotTwin,52018,M,mo_52018,fa_52018,hh_52018,,1
10,HCP102311,Twin,MZ,51679,F,mo_51679,fa_51679,hh_51679,pair_51679,2
11,HCP102513,NotTwin,NotTwin,56077,M,mo_56077,fa_56077,hh_56077,,1
12,HCP102816,Twin,MZ,51418,F,mo_51418,fa_51418,hh_51418,pair_51418,2
13,HCP103111,NotTwin,NotTwin,51351,M,mo_51351,fa_51351,hh_51351,,1
14,HCP103414,NotTwin,NotTwin,52198,F,mo_52198,fa_52198,hh_52198,,2
15,HCP103515,Twin,NotMZ,51537,F,mo_51537,fa_51537,hh_51537,,2
16,HCP103818,Twin,MZ,51343,F,mo_51343,fa_51343,hh_51343,pair_51343,2
17,HCP104416,Twin,MZ,54643,F,mo_54643,fa_54643,hh_54643,pair_54643,2
18,HCP104820,Twin,MZ,51283,F,mo_51283,fa_51283,hh_51283,pair_51283,2
19,HCP105014,Twin,NotMZ,51451,F,mo_51451,fa_51451,hh_51451,,2
20,HCP105115,Twin,NotMZ,51820,M,mo_51820,fa_51820,hh_51820,,1
21,HCP105216,NotTwin,NotTwin,51527,M,mo_51527,fa_51527,hh_51527,,1
22,HCP105620,NotTwin,NotTwin,55695,F,mo_55695,fa_55695,hh_55695,,2
23,HCP106016,Twin,NotMZ,52134,F,mo_52134,fa_52134,hh_52134,,2
24,HCP106319,NotTwin,NotTwin,51527,M,mo_51527,fa_51527,hh_51527,,1
25,HCP106521,Twin,NotMZ,51468,F,mo_51468,fa_51468,hh_51468,,2
26,HCP107018,Twin,MZ,51676,F,mo_51676,fa_51676,hh_51676,pair_51676,2
27,HCP107220,NotTwin,NotTwin,55705,F,mo_55705,fa_55705,hh_55705,,2
28,HCP107321,NotTwin,NotTwin,52493,F,mo_52493,fa_52493,hh_52493,,2
29,HCP107422,Twin,NotMZ,54628,M,mo_54628,fa_54628,hh_54628,,1
...,...,...,...,...,...,...,...,...,...,...
91,M_HCP123824,Twin,MZ,56022,M,mo_56022,fa_56022,hh_56022,pair_56022,1
94,M_HCP124422,Twin,MZ,51529,F,mo_51529,fa_51529,hh_51529,pair_51529,2
113,M_HCP130316,Twin,MZ,51559,F,mo_51559,fa_51559,hh_51559,pair_51559,2
114,M_HCP130417,Twin,MZ,52809,M,mo_52809,fa_52809,hh_52809,pair_52809,1
117,M_HCP130922,Twin,MZ,51527,F,mo_51527,fa_51527,hh_51527,pair_51527,2
150,M_HCP139233,Twin,MZ,51312,F,mo_51312,fa_51312,hh_51312,pair_51312,2
157,M_HCP141119,Twin,MZ,52823,M,mo_52823,fa_52823,hh_52823,pair_52823,1
173,M_HCP146533,Twin,MZ,52839,M,mo_52839,fa_52839,hh_52839,pair_52839,1
174,M_HCP146937,Twin,MZ,52938,F,mo_52938,fa_52938,hh_52938,pair_52938,2
208,M_HCP154532,Twin,MZ,52757,M,mo_52757,fa_52757,hh_52757,pair_52757,1
233,M_HCP159845,Twin,MZ,52926,F,mo_52926,fa_52926,hh_52926,pair_52926,2
243,M_HCP162733,Twin,MZ,51599,F,mo_51599,fa_51599,hh_51599,pair_51599,2
249,M_HCP164030,Twin,MZ,51785,M,mo_51785,fa_51785,hh_51785,pair_51785,1
255,M_HCP165638,Twin,MZ,52801,M,mo_52801,fa_52801,hh_52801,pair_52801,1
302,M_HCP177241,Twin,MZ,52793,M,mo_52793,fa_52793,hh_52793,pair_52793,1
307,M_HCP178243,Twin,MZ,56016,M,mo_56016,fa_56016,hh_56016,pair_56016,1
318,M_HCP180735,Twin,MZ,52884,F,mo_52884,fa_52884,hh_52884,pair_52884,2
335,M_HCP186141,Twin,MZ,51826,M,mo_51826,fa_51826,hh_51826,pair_51826,1
409,M_HCP209228,Twin,MZ,55706,F,mo_55706,fa_55706,hh_55706,pair_55706,2
420,M_HCP211922,Twin,MZ,51673,F,mo_51673,fa_51673,hh_51673,pair_51673,2
446,M_HCP239944,Twin,MZ,52141,F,mo_52141,fa_52141,hh_52141,pair_52141,2
489,M_HCP316835,Twin,MZ,55732,F,mo_55732,fa_55732,hh_55732,pair_55732,2
534,M_HCP395756,Twin,MZ,52913,F,mo_52913,fa_52913,hh_52913,pair_52913,2
600,M_HCP562345,Twin,MZ,52941,F,mo_52941,fa_52941,hh_52941,pair_52941,2
633,M_HCP599671,Twin,MZ,52795,M,mo_52795,fa_52795,hh_52795,pair_52795,1
696,M_HCP727553,Twin,MZ,51561,F,mo_51561,fa_51561,hh_51561,pair_51561,2
722,M_HCP769064,Twin,MZ,52803,M,mo_52803,fa_52803,hh_52803,pair_52803,1
748,M_HCP835657,Twin,MZ,52137,F,mo_52137,fa_52137,hh_52137,pair_52137,2
792,M_HCP904044,Twin,MZ,51290,F,mo_51290,fa_51290,hh_51290,pair_51290,2
818,M_HCP972566,Twin,MZ,56077,F,mo_56077,fa_56077,hh_56077,pair_56077,2

In [25]:
test.head()

,Subject,Twin_Stat,Zygosity,Mother_ID,Gender,mo,fa,hhID,mz_twin,sex
0,HCP100206,NotTwin,NotTwin,56037,M,mo_56037,fa_56037,hh_56037,,1
1,HCP100307,Twin,NotMZ,51488,F,mo_51488,fa_51488,hh_51488,,2
2,HCP100408,Twin,MZ,51730,M,mo_51730,fa_51730,hh_51730,pair_51730,1
3,HCP100610,Twin,NotMZ,52813,M,mo_52813,fa_52813,hh_52813,,1
4,HCP101006,Twin,MZ,51283,F,mo_51283,fa_51283,hh_51283,pair_51283,2

In [31]:
pedig_final = test[["Subject","fa","mo","sex","mz_twin","hhID"]]
pedig_final.rename(columns={'Subject':'ID'},inplace=True)

/usr/local/lib/python3.4/dist-packages/pandas/core/frame.py:2834: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  **kwargs)

In [32]:
pedig_final.head()

          ID        fa        mo  sex     mz_twin      hhID
0  HCP100206  fa_56037  mo_56037    1              hh_56037
1  HCP100307  fa_51488  mo_51488    2              hh_51488
2  HCP100408  fa_51730  mo_51730    1  pair_51730  hh_51730
3  HCP100610  fa_52813  mo_52813    1              hh_52813
4  HCP101006  fa_51283  mo_51283    2  pair_51283  hh_51283

In [33]:
# Save the pedigree file
pedig_final.to_csv(os.path.join(out_path,"solar_motor_RL_pedigre.csv"), index=False)